name: NPX Claude Spawning Test
on:
  workflow_dispatch:
    inputs:
      test_task:
        description: "Task for Claude agent"
        required: true
        default: "analyze repository structure and suggest improvements"

jobs:
  npx-claude-spawn-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
        continue-on-error: true

      - name: NPX Claude Spawning Test
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        continue-on-error: true
        run: |
          echo "Testing NPX Claude spawning with expect patterns..."
          cd ~ && nix-shell -p nodejs expect --run 'expect -c "
            set timeout 600
            spawn npx @anthropic-ai/claude-code --dangerously-skip-permissions \"${{ github.event.inputs.test_task }}\"
            expect {
              -re {.*bypass permissions.*} {
                send \"2\r\"
                exp_continue
              }
              -re {.*Write.*|.*created.*|.*analysis.*} {
                puts \"✅ Claude agent execution successful\"
                exit 0
              }
              timeout {
                puts \"❌ Agent execution timeout\"
                exit 1
              }
            }
          "'

      - name: Ubuntu Fallback Test
        if: failure()
        run: |
          echo "Testing Ubuntu fallback approach..."
          sudo apt-get update -qq
          sudo apt-get install -y nodejs npm curl
          echo "✅ Ubuntu environment ready for NPX testing"
          
          # Test direct NPX without expect (simpler approach)
          timeout 300 npx --yes @anthropic-ai/claude-code --version || echo "NPX test completed"

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: npx-test-results
          path: |
            *.txt
            *.log
